@startuml OfferingDoc_FeeTables

'******* CONFIGURATION ************************************************
!include style.uml.inc


'******* CLASS DEFINITION *********************************************

/' enum OfferingDocumentSections <<enumeration>>{ '/
/' 	feeTable '/
/' 	onGoingCostIllustrations '/
/' 	illustrativeExample '/
/' } '/

enum JoiningAndAnnualFeesExpensesCharges <<enumeration>>{
	joining_fee
	annual_fee
}

enum TransactionsInIndividualMembersAccountFeesExpensesCharges <<enumeration>>{
	contribution_charge
	offer_spread
	bid_spread
	withdrawal_charge
}

enum ConstituentFundFeesExpensesCharges <<enumeration>>{
	management_fees
	guarantee_charge
	other_expenses
}

class PayableEntity {
}

class FeeTable {
}

class TabularFeeTable {
	+feeRows: FeeRow[0..*]
}
class FreeFormFeeTable {
	+description: String[0..1]
}

class FeeRow {
	+currentLevel: FeeClass[1..*]
}

class FeeClass {
	+name: String
	+value: Amount
}

class JoiningAnnualFeeRow {
	+payableBy: PayableEntity[0..1]
}

class JoiningFeeRow {
	+feeType: JoiningAndAnnualFeesExpensesCharges = "joining_fee"
}

class AnnualFeeRow {
	+feeType: JoiningAndAnnualFeesExpensesCharges = "annual_fee"
}

class JoiningAnnualFeeTable {
	+joiningFee: JoiningFeeRow
	+annualFee: AnnualFeeRow
}

class FundFeeRow {
	+fundName: String
	+feeType: TransactionsInIndividualMembersAccountFeesExpensesCharges
	+payableBy: PayableEntity[0..1]
}

class TransactionsInIndividualMembersAccountFeeTable {
	+feeRows: FundFeeRow[1..*]
}

class ConstituentFundManagementFeesFeeRow {
	+fundName: String
	+feeType: ConstituentFundFeesExpensesCharges = "management_fees"
	+deductedFrom: PayableEntity[0..1]
}

class ConstituentFundGuaranteeChargeFeeRow {
	+fundName: String
	+feeType: ConstituentFundFeesExpensesCharges = "guarantee_charge"
	+deductedFrom: PayableEntity[0..1]
}

class ConstituentFundOtherExpensesFeeRow {
	+description: String
	+feeType: ConstituentFundFeesExpensesCharges = "other_expenses"
}

class ConstituentFundsFeeTable {
	+managementFees: ConstituentFundManagementFeesFeeRow[1..*]
	+guaranteeCharge: ConstituentFundGuaranteeChargeFeeRow[0..*]
	+otherExpenses: ConstituentFundOtherExpensesFeeRow
}

class UnderlyingFundsFeeTable {
	+description: String
}

class OtherFeesFeeTable {
	+description: String
}

'******* NOTES ********************************************************

'******* CLASS RELATIONS **********************************************
BasicDocument <|-- OfferingDocument
FeeTable <|-- JoiningAnnualFeeTable
FeeTable <|-- TransactionsInIndividualMembersAccountFeeTable
FeeTable <|-- ConstituentFundsFeeTable
FeeTable <|-- UnderlyingFundsFeeTable
FeeRow <|-- JoiningAnnualFeeRow
JoiningAnnualFeeRow <|-- JoiningFeeRow
JoiningAnnualFeeRow <|-- AnnualFeeRow
FeeRow <|-- FundFeeRow
FeeRow <|-- ConstituentFundManagementFeesFeeRow
FeeRow <|-- ConstituentFundGuaranteeChargeFeeRow
FeeRow <|-- ConstituentFundOtherExpensesFeeRow
@enduml
