@startuml OfferingDoc_Sections

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class BasicSection <<BasicDocument>> {
}

class HierarchicalSection <<BasicDocument>> {
}

class OfferingDocSection {
	+status: NormativeType
}

class OfferingDocSHierarchicalection {
	+subsections: OfferingDocSection[0..*]
}

class OfferingDocContentSection {
}

class ClauseSection {
	+subsections: ClauseSection[0..*]
}

class GlossarySection {
	+terms: <<Term>>TermCollection
}

class DefinitionSection {
	+definitions: <<Term>>DefinitionCollection
}

class AnnexSection {
	+subsections: ClauseSection[0..*]
}

' TODO:'
class UpfrontRiskDisclosureStatementSection {
}

' TODO:'
class DirectoryOfApprovedTrusteeAndOtherServiceProvidersSection {
}

' TODO:'
class FundOptionsInvestmentObjectivesAndPoliciesSection {
}

' TODO:'
class RisksSection {
}

class FeesAndChargesSection {
	+feeTables: FeeTable[1..*]
	+definitions: DefinitionSection
}

' TODO:'
class AdministrativeProceduresSection {
}

' TODO:'
class OtherInformationSection {
}

class StandardReferencesSection {
	references: <<Bibliography>>BibliographicItem[0..*]
}

enum NormativeType <<enumeration>> {
	normative
	informative
}

' TODO:'

'******* NOTES ********************************************************
note "OfferingDocHierarchicalSection, OfferingDocContentSection\nand StandardReferencesSection differ from those of\nBasicDocument with having an extra 'obligation' attribute" as N1
note bottom of OfferingDocHierarchicalSection: Non-clause sections are\nmodeled as\nStandardContentSections.\nExample: Introduction, Foreword.
note top of ClauseSection: Subclauses are\nmutually exclusive\nwith text content
note bottom of GlossarySection: A GlossarySection or DefinitionSection\nis a leaf node - only contain terms\nor symbols/abbreviations. The\ncontent of each solely comes from\nthe terms or symbols/abbreviations.
note bottom of AnnexSection: Annex and its children\nclauses permit\nhanging paragraphs\n(as is 'blocks').
note bottom of StandardReferencesSection: A referencesSection is also a leaf node.

'******* CLASS RELATIONS **********************************************
BasicSection <|-- OfferingDocSection

OfferingDocSection <-left- NormativeType
OfferingDocSection <|-- OfferingDocHierarchicalSection
OfferingDocSection <|-- ClauseSection
OfferingDocSection <|-- AnnexSection
OfferingDocSection <|-- StandardReferencesSection

OfferingDocHierarchicalSection <|-- OfferingDocContentSection

OfferingDocSection <|-- UpfrontRiskDisclosureStatementSection
OfferingDocSection <|-- DirectoryOfApprovedTrusteeAndOtherServiceProvidersSection
OfferingDocSection <|-- FundOptionsInvestmentObjectivesAndPoliciesSection
OfferingDocSection <|-- RisksSection
OfferingDocSection <|-- FeesAndChargesSection
OfferingDocSection <|-- AdministrativeProceduresSection
OfferingDocSection <|-- OtherInformationSection

ClauseSection <|-- GlossarySection
ClauseSection <|-- DefinitionSection

@enduml
