# RNG Configuration

files:
  - ../grammars/basicdoc.rnc
  - ../grammars/biblio.rnc
  - ../grammars/biblio-standoc.rnc
  - ../grammars/biblio-presentation.rnc
  - ../grammars/standoc.rnc
  - ../grammars/gbstandard.rnc
  - ../grammars/relaton-gb-compile.rnc
