# RNG Configuration

files:
  - ../grammars/basicdoc.rnc
  - ../grammars/biblio.rnc
  - ../grammars/biblio-standdoc.rnc
  - ../grammars/biblio-presentation.rnc
  - ../grammars/relaton-iso-compile.rnc
  - ../grammars/standoc-compile.rnc
  - ../grammars/standoc-presentation-compile.rnc
