# RNG Configuration

files:
  - ../grammars/basicdoc.rnc
  - ../grammars/biblio.rnc
  - ../grammars/biblio-standoc.rnc
  - ../grammars/biblio-presentation.rnc
  - ../grammars/standoc.rnc
  - ../grammars/isostandard.rnc
  - ../grammars/relaton-iso-compile.rnc
