# RNG Configuration

files:
  - ../grammars/basicdoc.rnc
  - ../grammars/biblio.rnc
  - ../grammars/biblio-standoc.rnc
  - ../grammars/biblio-presentation.rnc
  - ../grammars/standoc.rnc
  - ../grammars/bipm.rnc
  - ../grammars/relaton-bipm-compile.rnc
