# RNG Configuration

files:
  - ../grammars/basicdoc.rnc
  - ../grammars/biblio.rnc
  - ../grammars/biblio-standoc.rnc
  - ../grammars/biblio-presentation.rnc
  - ../grammars/standoc.rnc
  - ../grammars/un.rnc
  - ../grammars/relaton-un-compile.rnc
