@startuml IhoBibliographicItem

'******* CONFIGURATION ************************************************
!include style.uml.inc


'******* CLASS DEFINITION *********************************************
class BibliographicItem <<StandardDocument>>{

}

class IhoBibliographicItem {
    +projectGroup: IhoProjectTeam[1..*]
    +type: IhoDocumentType
    +title: FormattedString
}

class IhoProjectTeam{
    +committee: IhoCommittee
    +workgroup: IhoWorkingGroup
}

enum IhoCommittee <<enumeration>>{
    hssc
    ircc
}

class IhoWorkingGroup{
    +name: FormattedString
}

class DocumentStatus{
    +status: IhoStatusType
}

enum IhoStatusType <<enumeration>>{
    proposal-draft
    development-draft
    testing-draft
    implementation-draft
    in-force
    retired
}

enum IhoDocumentType <<enumeration>>{
    bathymetric
    capacity
    misc
    periodic
    standards
}

'******* NOTES ********************************************************

note bottom of IhoDocumentType: * B: Bathymetric Publications\n* C: Capacity Building Publications\n* P: Periodic Publications\n* S: Standards and Specifications\n* misc: Miscellaneous Publications (including Basic Documents)

note bottom of IhoStatusType: * Proposed Phase Draft\n* Development Phase Draft ("Draft Publications for discussion")\n* Testing Phase Draft\n* Implementation Stage Draft ("Draft Publications awaiting approval by Member States")\n* In-force publications:\n** In-force but prior to effective date ("Draft Publications in the final stage of editing following adoption by Member States")\n** In-force and effective\n* Retired publications

note bottom of IhoCommittee: * Hydrographic Services and Standards Committee (HSSC)\n* Inter-Regional Coordination Committee (IRCC)

'******* CLASS RELATIONS **********************************************
BibliographicItem <|-- IhoBibliographicItem

IhoBibliographicItem <-- IhoProjectTeam
IhoBibliographicItem <-- IhoDocumentType
IhoBibliographicItem <-- DocumentStatus

IhoProjectTeam <-- IhoCommittee
IhoProjectTeam <-- IhoWorkingGroup

DocumentStatus <-- IhoStatusType

@enduml
