@startuml IhoBibliographicItem

'******* CONFIGURATION ************************************************
!include style.uml.inc


'******* CLASS DEFINITION *********************************************
class BibliographicItem <<StandardDocument>>{

}

class IhoBibliographicItem {
    +projectGroup: IhoProjectTeam[1..*]
    +type: IhoDocumentType
    +title: FormattedString
}

class IhoProjectTeam{
    +committee: IhoCommittee
    +workgroup: IhoWorkingGroup
}

enum IhoCommittee <<enumeration>>{
    hssc
}

class IhoWorkingGroup{
    +name: FormattedString
}

class DocumentStatus{
    +status: IhoStatusType
}

enum IhoStatusType <<enumeration>>{
    draft
    discussion-draft
    approval-draft
    final-draft
    in-force
    retired
}

enum IhoDocumentType <<enumeration>>{
    bathymetric
    capacity
    misc
    periodic
    standards
}

'******* NOTES ********************************************************

note bottom of IhoDocumentType: * B: Bathymetric Publications\n* C: Capacity Building Publications\n* P: Periodic Publications\n* S: Standards and Specifications\n* misc: Miscellaneous Publications (including Basic Documents)

note bottom of IhoStatusType: * Unpublished Drafts\n* Draft Publications for discussion\n* Draft Publications awaiting approval by Member States\n* Draft Publications in the final stage of editing following adoption by Member States\n* In-force publications\n* Retired publications\n


'******* CLASS RELATIONS **********************************************
BibliographicItem <|-- IhoBibliographicItem

IhoBibliographicItem <-- IhoProjectTeam
IhoBibliographicItem <-- IhoDocumentType
IhoBibliographicItem <-- DocumentStatus

IhoProjectTeam <-- IhoCommittee
IhoProjectTeam <-- IhoWorkingGroup

DocumentStatus <-- IhoStatusType

@enduml
