# RNG Configuration

files:
  - ../grammars/basicdoc.rnc
  - ../grammars/biblio.rnc
  - ../grammars/biblio-standdoc.rnc
  - ../grammars/biblio-presentation.rnc
  - ../grammars/standoc.rnc
  - ../grammars/itu.rnc
  - ../grammars/relaton-itu-compile.rnc
